// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// categorize_cell_specificity
std::string categorize_cell_specificity(CharacterVector significant_cts, CharacterVector specificity_categories, Nullable<NumericVector> lfsr_values, Nullable<CharacterVector> lfsr_names, List lineage_groups, List subgroup_levels, CharacterVector bulk_cts, CharacterVector other_cts, double lfsr_sig_threshold, double lfsr_null_threshold);
RcppExport SEXP _cascade_categorize_cell_specificity(SEXP significant_ctsSEXP, SEXP specificity_categoriesSEXP, SEXP lfsr_valuesSEXP, SEXP lfsr_namesSEXP, SEXP lineage_groupsSEXP, SEXP subgroup_levelsSEXP, SEXP bulk_ctsSEXP, SEXP other_ctsSEXP, SEXP lfsr_sig_thresholdSEXP, SEXP lfsr_null_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type significant_cts(significant_ctsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type specificity_categories(specificity_categoriesSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lfsr_values(lfsr_valuesSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type lfsr_names(lfsr_namesSEXP);
    Rcpp::traits::input_parameter< List >::type lineage_groups(lineage_groupsSEXP);
    Rcpp::traits::input_parameter< List >::type subgroup_levels(subgroup_levelsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bulk_cts(bulk_ctsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type other_cts(other_ctsSEXP);
    Rcpp::traits::input_parameter< double >::type lfsr_sig_threshold(lfsr_sig_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type lfsr_null_threshold(lfsr_null_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(categorize_cell_specificity(significant_cts, specificity_categories, lfsr_values, lfsr_names, lineage_groups, subgroup_levels, bulk_cts, other_cts, lfsr_sig_threshold, lfsr_null_threshold));
    return rcpp_result_gen;
END_RCPP
}
// categorize_features_from_acat
DataFrame categorize_features_from_acat(DataFrame acat_matrix, CharacterVector specificity_categories, Nullable<DataFrame> lfsr_lookup, std::string feature_type, Nullable<List> l2_to_l1_mapping, List lineage_groups, List subgroup_levels, CharacterVector bulk_cts, CharacterVector other_cts, double sig_threshold, double lfsr_null_threshold);
RcppExport SEXP _cascade_categorize_features_from_acat(SEXP acat_matrixSEXP, SEXP specificity_categoriesSEXP, SEXP lfsr_lookupSEXP, SEXP feature_typeSEXP, SEXP l2_to_l1_mappingSEXP, SEXP lineage_groupsSEXP, SEXP subgroup_levelsSEXP, SEXP bulk_ctsSEXP, SEXP other_ctsSEXP, SEXP sig_thresholdSEXP, SEXP lfsr_null_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type acat_matrix(acat_matrixSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type specificity_categories(specificity_categoriesSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type lfsr_lookup(lfsr_lookupSEXP);
    Rcpp::traits::input_parameter< std::string >::type feature_type(feature_typeSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type l2_to_l1_mapping(l2_to_l1_mappingSEXP);
    Rcpp::traits::input_parameter< List >::type lineage_groups(lineage_groupsSEXP);
    Rcpp::traits::input_parameter< List >::type subgroup_levels(subgroup_levelsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bulk_cts(bulk_ctsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type other_cts(other_ctsSEXP);
    Rcpp::traits::input_parameter< double >::type sig_threshold(sig_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type lfsr_null_threshold(lfsr_null_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(categorize_features_from_acat(acat_matrix, specificity_categories, lfsr_lookup, feature_type, l2_to_l1_mapping, lineage_groups, subgroup_levels, bulk_cts, other_cts, sig_threshold, lfsr_null_threshold));
    return rcpp_result_gen;
END_RCPP
}
// categorize_variants_bulk_cpp
CharacterVector categorize_variants_bulk_cpp(DataFrame variant_results, CharacterVector specificity_categories, Nullable<DataFrame> lfsr_lookup_results, Nullable<List> l2_to_l1_mapping, List lineage_groups, List subgroup_levels, CharacterVector bulk_cts, CharacterVector other_cts, double lfsr_sig_threshold, double lfsr_null_threshold);
RcppExport SEXP _cascade_categorize_variants_bulk_cpp(SEXP variant_resultsSEXP, SEXP specificity_categoriesSEXP, SEXP lfsr_lookup_resultsSEXP, SEXP l2_to_l1_mappingSEXP, SEXP lineage_groupsSEXP, SEXP subgroup_levelsSEXP, SEXP bulk_ctsSEXP, SEXP other_ctsSEXP, SEXP lfsr_sig_thresholdSEXP, SEXP lfsr_null_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type variant_results(variant_resultsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type specificity_categories(specificity_categoriesSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type lfsr_lookup_results(lfsr_lookup_resultsSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type l2_to_l1_mapping(l2_to_l1_mappingSEXP);
    Rcpp::traits::input_parameter< List >::type lineage_groups(lineage_groupsSEXP);
    Rcpp::traits::input_parameter< List >::type subgroup_levels(subgroup_levelsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bulk_cts(bulk_ctsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type other_cts(other_ctsSEXP);
    Rcpp::traits::input_parameter< double >::type lfsr_sig_threshold(lfsr_sig_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type lfsr_null_threshold(lfsr_null_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(categorize_variants_bulk_cpp(variant_results, specificity_categories, lfsr_lookup_results, l2_to_l1_mapping, lineage_groups, subgroup_levels, bulk_cts, other_cts, lfsr_sig_threshold, lfsr_null_threshold));
    return rcpp_result_gen;
END_RCPP
}
// detect_variant_qtl_patterns
List detect_variant_qtl_patterns(CharacterVector variant_ids, List variant_matrix_data, DataFrame peak_gene_links, CharacterVector cell_types, int ct_idx, CharacterVector qtl_mechanism_categories, IntegerVector pattern_to_mechanism, List caqtl_status_values, List eqtl_status_values);
RcppExport SEXP _cascade_detect_variant_qtl_patterns(SEXP variant_idsSEXP, SEXP variant_matrix_dataSEXP, SEXP peak_gene_linksSEXP, SEXP cell_typesSEXP, SEXP ct_idxSEXP, SEXP qtl_mechanism_categoriesSEXP, SEXP pattern_to_mechanismSEXP, SEXP caqtl_status_valuesSEXP, SEXP eqtl_status_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type variant_ids(variant_idsSEXP);
    Rcpp::traits::input_parameter< List >::type variant_matrix_data(variant_matrix_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type peak_gene_links(peak_gene_linksSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cell_types(cell_typesSEXP);
    Rcpp::traits::input_parameter< int >::type ct_idx(ct_idxSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type qtl_mechanism_categories(qtl_mechanism_categoriesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pattern_to_mechanism(pattern_to_mechanismSEXP);
    Rcpp::traits::input_parameter< List >::type caqtl_status_values(caqtl_status_valuesSEXP);
    Rcpp::traits::input_parameter< List >::type eqtl_status_values(eqtl_status_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_variant_qtl_patterns(variant_ids, variant_matrix_data, peak_gene_links, cell_types, ct_idx, qtl_mechanism_categories, pattern_to_mechanism, caqtl_status_values, eqtl_status_values));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cascade_categorize_cell_specificity", (DL_FUNC) &_cascade_categorize_cell_specificity, 10},
    {"_cascade_categorize_features_from_acat", (DL_FUNC) &_cascade_categorize_features_from_acat, 11},
    {"_cascade_categorize_variants_bulk_cpp", (DL_FUNC) &_cascade_categorize_variants_bulk_cpp, 10},
    {"_cascade_detect_variant_qtl_patterns", (DL_FUNC) &_cascade_detect_variant_qtl_patterns, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_cascade(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
