# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

categorize_cell_specificity <- function(significant_cts, specificity_categories, lfsr_values = NULL, lfsr_names = NULL, lineage_groups, subgroup_levels, bulk_cts = as.character( c()), other_cts = as.character( c()), lfsr_sig_threshold = 0.05, lfsr_null_threshold = 0.5) {
    .Call(`_cascade_categorize_cell_specificity`, significant_cts, specificity_categories, lfsr_values, lfsr_names, lineage_groups, subgroup_levels, bulk_cts, other_cts, lfsr_sig_threshold, lfsr_null_threshold)
}

categorize_features_from_acat <- function(acat_matrix, specificity_categories, lfsr_lookup = NULL, feature_type = "gene", l2_to_l1_mapping = NULL, lineage_groups, subgroup_levels, bulk_cts = as.character( c()), other_cts = as.character( c()), sig_threshold = 0.05, lfsr_null_threshold = 0.5) {
    .Call(`_cascade_categorize_features_from_acat`, acat_matrix, specificity_categories, lfsr_lookup, feature_type, l2_to_l1_mapping, lineage_groups, subgroup_levels, bulk_cts, other_cts, sig_threshold, lfsr_null_threshold)
}

categorize_variants_bulk_cpp <- function(variant_results, specificity_categories, lfsr_lookup_results = NULL, l2_to_l1_mapping = NULL, lineage_groups, subgroup_levels, bulk_cts = as.character( c()), other_cts = as.character( c()), lfsr_sig_threshold = 0.05, lfsr_null_threshold = 0.5) {
    .Call(`_cascade_categorize_variants_bulk_cpp`, variant_results, specificity_categories, lfsr_lookup_results, l2_to_l1_mapping, lineage_groups, subgroup_levels, bulk_cts, other_cts, lfsr_sig_threshold, lfsr_null_threshold)
}

detect_variant_qtl_patterns <- function(variant_ids, variant_matrix_data, peak_gene_links, cell_types, ct_idx, qtl_mechanism_categories = as.character( c(         "Local Cascade", "Positional Cascade", "Distal Cascade",         "caQTL + eQTL (No Link)", "Only caQTL (With Link)",         "Only caQTL (No Link)", "Only eQTL", "No molQTL")), pattern_to_mechanism = as.integer( c(         1, 2, 2, 2, 3, 4, 4, 4, 4, 4,           4, 4, 5, 5, 5, 5, 6, 6, 6, 7,           7, 7, 8, 8, 8                           )), caqtl_status_values, eqtl_status_values) {
    .Call(`_cascade_detect_variant_qtl_patterns`, variant_ids, variant_matrix_data, peak_gene_links, cell_types, ct_idx, qtl_mechanism_categories, pattern_to_mechanism, caqtl_status_values, eqtl_status_values)
}

